name: moyasar
description: Accept payments in your Flutter app with ease by using Moyasar. With this SDK, you can quickly and safely accept payments through Apple Pay and Credit Card (with managed 3DS step).
version: 2.0.2
homepage: https://moyasar.com/en/
repository: https://github.com/moyasar/moyasar-flutter
issue_tracker: https://github.com/moyasar/moyasar-flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.3"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  pay: ^1.1.2
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
